{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "VIOS ",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "3.1"
                        }
                    ]
                },
                {
                    "product": "AIX",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "7.1"
                        },
                        {
                            "status": "affected",
                            "version": "7.2"
                        },
                        {
                            "status": "affected",
                            "version": "7.3"
                        }
                    ]
                }
            ],
            "datePublic": "2022-03-04T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM AIX 7.1, 7.2, 7.3, and VIOS 3.1 could allow a non-privileged local user to exploit a vulnerability in the AIX kernel to cause a denial of service. IBM X-Force ID: 212950."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.2,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 5.4,
                        "temporalSeverity": "MEDIUM",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/PR:N/AC:L/A:H/S:U/AV:L/C:N/I:N/UI:N/RL:O/RC:C/E:U",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Denial of Service",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-03-07T16:55:13",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/pages/node/6561281"
                },
                {
                    "name": "ibm-aix-cve202138988-dos (212950)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/212950"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2021-38988",
        "dateReserved": "2021-08-16T00:00:00",
        "dateUpdated": "2022-03-07T16:55:13",
        "state": "PUBLISHED",
        "datePublished": "2022-03-07T16:55:14.019646Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
