{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Maximo Asset Management",
                    "vendor": "IBM",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "7.6.1.1"
                        }
                    ]
                }
            ],
            "datePublic": "2019-10-08T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "IBM Maximo Asset Management 7.6.1.1 generates an error message that includes sensitive information that could be used in further attacks against the system. IBM X-Force ID: 164554."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "NONE",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "exploitCodeMaturity": "UNPROVEN",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "remediationLevel": "OFFICIAL_FIX",
                        "reportConfidence": "CONFIRMED",
                        "scope": "UNCHANGED",
                        "temporalScore": 3.8,
                        "temporalSeverity": "LOW",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/I:N/C:L/S:U/UI:N/A:N/PR:L/AC:L/RC:C/E:U/RL:O",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Obtain Information",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2019-10-09T15:00:23",
                "orgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
                "shortName": "ibm"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.ibm.com/support/pages/node/1075413"
                },
                {
                    "name": "ibm-maximo-cve20194512-info-disc (164554)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/164554"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "9a959283-ebb5-44b6-b705-dcc2bbced522",
        "assignerShortName": "ibm",
        "cveId": "CVE-2019-4512",
        "dateReserved": "2019-01-03T00:00:00",
        "dateUpdated": "2019-10-09T15:00:23",
        "state": "PUBLISHED",
        "datePublished": "2019-10-09T15:00:23.883418Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
