{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "pimcore/pimcore",
                    "vendor": "pimcore",
                    "versions": [
                        {
                            "lessThan": "10.2.7",
                            "status": "affected",
                            "version": "unspecified",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Unrestricted Upload of File with Dangerous Type in Packagist pimcore/pimcore prior to 10.2.7."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.6,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:H",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-434",
                            "description": "CWE-434 Unrestricted Upload of File with Dangerous Type",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-18T15:55:10",
                "orgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
                "shortName": "@huntrdev"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://huntr.dev/bounties/96506857-06bc-4c84-88b7-4f397715bcf6"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/pimcore/pimcore/commit/35d1853baf64d6a1d90fd8803e52439da53a3911"
                }
            ],
            "source": {
                "advisory": "96506857-06bc-4c84-88b7-4f397715bcf6",
                "discovery": "EXTERNAL"
            },
            "title": "Unrestricted Upload of File with Dangerous Type in pimcore/pimcore"
        }
    },
    "cveMetadata": {
        "assignerOrgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
        "assignerShortName": "@huntrdev",
        "cveId": "CVE-2022-0263",
        "datePublished": "2022-01-18T15:55:10",
        "dateReserved": "2022-01-17T00:00:00",
        "dateUpdated": "2022-01-18T15:55:10",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
