{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Routing",
                    "vendor": "Cloud Foundry",
                    "versions": [
                        {
                            "lessThan": "0.204.0",
                            "status": "affected",
                            "version": "All",
                            "versionType": "custom"
                        }
                    ]
                },
                {
                    "product": "CF Deployment",
                    "vendor": "Cloud Foundry",
                    "versions": [
                        {
                            "lessThan": "13.13.0",
                            "status": "affected",
                            "version": "All",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "datePublic": "2020-08-14T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Cloud Foundry Routing (Gorouter), versions prior to 0.204.0, when used in a deployment with NGINX reverse proxies in front of the Gorouters, is potentially vulnerable to denial-of-service attacks in which an unauthenticated malicious attacker can send specially-crafted HTTP requests that may cause the Gorouters to be dropped from the NGINX backend pool."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.7,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "CHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:H",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-404",
                            "description": "CWE-404: Improper Resource Shutdown or Release",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-08-21T21:50:14",
                "orgId": "862b2186-222f-48b9-af87-f1fb7bb26d03",
                "shortName": "pivotal"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.cloudfoundry.org/blog/cve-2020-5416"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "CF clusters with NGINX in front of them may be vulnerable to DoS"
        }
    },
    "cveMetadata": {
        "assignerOrgId": "862b2186-222f-48b9-af87-f1fb7bb26d03",
        "assignerShortName": "pivotal",
        "cveId": "CVE-2020-5416",
        "dateReserved": "2020-01-03T00:00:00",
        "dateUpdated": "2020-08-21T21:50:14",
        "state": "PUBLISHED",
        "datePublished": "2020-08-21T21:50:14.375704Z"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
