{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "cveId": "CVE-2024-3772",
        "assignerOrgId": "430a6cef-dc26-47e3-9fa8-52fb7f19644e",
        "state": "PUBLISHED",
        "assignerShortName": "directcyber",
        "dateReserved": "2024-04-15T01:23:15.783Z",
        "datePublished": "2024-04-15T01:42:07.888Z",
        "dateUpdated": "2024-04-22T19:29:11.444Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "Pydantic",
                    "repo": "https://github.com/pydantic/pydantic",
                    "vendor": "Pydantic",
                    "versions": [
                        {
                            "lessThan": "2.4.0",
                            "status": "affected",
                            "version": "2.0",
                            "versionType": "semver"
                        },
                        {
                            "lessThan": "1.10.13",
                            "status": "affected",
                            "version": "1.0",
                            "versionType": "semver"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "Sajeeb Lohani"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "Regular expression denial of service in Pydanic &lt; 2.4.0, &lt; 1.10.13 allows remote attackers to cause denial of service via a crafted email string.<br>"
                        }
                    ],
                    "value": "Regular expression denial of service in Pydanic < 2.4.0, < 1.10.13 allows remote attackers to cause denial of service via a crafted email string.\n"
                }
            ],
            "impacts": [
                {
                    "descriptions": [
                        {
                            "lang": "en",
                            "value": "Denial of Service"
                        }
                    ]
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "HIGH",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 5.9,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ]
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-1333",
                            "description": "CWE-1333 Inefficient Regular Expression Complexity",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "430a6cef-dc26-47e3-9fa8-52fb7f19644e",
                "shortName": "directcyber",
                "dateUpdated": "2024-04-22T19:29:11.444Z"
            },
            "references": [
                {
                    "url": "https://github.com/pydantic/pydantic/pull/7360"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Regular expression denial of service in Pydantic < 2.4.0",
            "x_generator": {
                "engine": "Vulnogram 0.1.0-dev"
            }
        }
    }
}
