{
    "containers": {
        "cna": {
            "affected": [
                {
                    "collection_url": "python-kdcproxy",
                    "cpes": [
                        "cpe:/o:redhat:enterprise_linux:7"
                    ],
                    "defaultStatus": "unaffected",
                    "product": "Red Hat Enterprise Linux 7",
                    "vendor": "Red Hat",
                    "x_redhatStatus": "Not affected"
                },
                {
                    "collection_url": "https://packages.fedoraproject.org/",
                    "defaultStatus": "affected",
                    "packageName": "python-kdcproxy",
                    "product": "Fedora",
                    "vendor": "Fedora",
                    "x_redhatStatus": "Affected"
                },
                {
                    "collection_url": "https://packages.fedoraproject.org/",
                    "defaultStatus": "affected",
                    "packageName": "python-kdcproxy",
                    "product": "Extra Packages for Enterprise Linux 7",
                    "vendor": "Fedora",
                    "x_redhatStatus": "Affected"
                }
            ],
            "datePublic": "2015-07-21T00:00:00Z",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "CVE-2015-5159 python-kdcproxy: Missing request size limit allows denial of service"
                }
            ],
            "metrics": [
                {
                    "other": {
                        "content": {
                            "namespace": "https://access.redhat.com/security/updates/classification/",
                            "value": "Low"
                        },
                        "type": "Red Hat severity rating"
                    }
                },
                {
                    "cvssV2_0": {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "availabilityRequirement": "NOT_DEFINED",
                        "baseScore": 5,
                        "collateralDamagePotential": "NOT_DEFINED",
                        "confidentialityImpact": "NONE",
                        "confidentialityRequirement": "NOT_DEFINED",
                        "environmentalScore": 0,
                        "exploitability": "NOT_DEFINED",
                        "integrityImpact": "NONE",
                        "integrityRequirement": "NOT_DEFINED",
                        "remediationLevel": "NOT_DEFINED",
                        "reportConfidence": "NOT_DEFINED",
                        "targetDistribution": "NOT_DEFINED",
                        "temporalScore": 0,
                        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
                        "version": "2.0"
                    },
                    "format": "CVSS"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-400",
                            "description": "Uncontrolled Resource Consumption",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat",
                "dateUpdated": "2023-02-02T14:01:12.750Z"
            },
            "references": [
                {
                    "tags": [
                        "vdb-entry",
                        "x_redhatRef"
                    ],
                    "url": "https://access.redhat.com/security/cve/CVE-2015-5159"
                },
                {
                    "name": "RHBZ#1245200",
                    "tags": [
                        "issue-tracking",
                        "x_redhatRef"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
                }
            ],
            "timeline": [
                {
                    "lang": "en",
                    "time": "2015-07-21T00:00:00Z",
                    "value": "Reported to Red Hat."
                },
                {
                    "lang": "en",
                    "time": "2015-07-21T00:00:00Z",
                    "value": "Made public."
                }
            ],
            "title": "CVE-2015-5159 python-kdcproxy: Missing request size limit allows denial of service",
            "workarounds": [
                {
                    "lang": "en",
                    "value": "Add \u201cLimitRequestBody 100000\u201d to the <Location> stanza, like this:\n\n    <Location \"/KdcProxy\">\n        Satisfy Any\n        Order Deny,Allow\n        Allow from all\n        WSGIProcessGroup kdcproxy\n        WSGIApplicationGroup kdcproxy\n        LimitRequestBody 100000\n    </Location>"
                }
            ],
            "x_redHatCweChain": "CWE-400: Uncontrolled Resource Consumption"
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2015-5159",
        "datePublished": "2018-10-30T18:00:00",
        "dateReserved": "2015-07-01T00:00:00",
        "dateUpdated": "2023-02-02T14:01:12.750Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}
